### ISSUE TITLE
java.util.NoSuchElementException - QueryInventoryFinishedListener

### ISSUE THREAD

**Issue by imaffett** [Wizcorp/phonegap-plugin-wizPurchase#18]
QueryInventoryFinishedListener fails for entries which are not the first element in SkuDetails sku : skuList

The following code fails because it calls next on the iterator inside the sku iterator
```
//This should be caching each entry in requestSkuIter and looping through skuList
if (!sku.getSku().equalsIgnoreCase(requestSkuIter.next()) ) { 
```

Below is the stack trace

```
08-29 10:11:47.222: E/AndroidRuntime(9018): java.util.NoSuchElementException
08-29 10:11:47.222: E/AndroidRuntime(9018): 	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:576)
08-29 10:11:47.222: E/AndroidRuntime(9018): 	at jp.wizcorp.phonegap.plugin.wizPurchase.WizPurchasePlugin$2.onQueryInventoryFinished(WizPurchasePlugin.java:523)
08-29 10:11:47.222: E/AndroidRuntime(9018): 	at com.smartmobilesoftware.util.IabHelper$2$1.run(IabHelper.java:630)
```

**Comment by jrouault** [comment]
Fixed in #39
